services:
  smarttaskmanagementapi:
    image: smarttaskmanagementapi
    build:
      context: .
      dockerfile: SmartTaskManagementAPI/Dockerfile
  redis:
    image: redis
    ports:
      - "6379:6379"

